name: Release 🚀

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.repository == '3liz/qgis-server-wmts-cache-plugin'

    steps:

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python requirements
        run: pip install -r .github/requirements.txt

      - name: Get current changelog
        run: qgis-plugin-ci changelog ${{ env.RELEASE_VERSION }} >> release.md

      - name: Create release on GitHub
        uses: ncipollo/release-action@v1.8.6
        with:
          bodyFile: release.md
          token: ${{ secrets.BOT_HUB_TOKEN }}

      - name: Package the plugin and deploy it in the release
        run: >-
          qgis-plugin-ci
          release ${{ env.RELEASE_VERSION }}
          --github-token ${{ secrets.BOT_HUB_TOKEN }}
          --osgeo-username ${{ secrets.OSGEO_USERNAME }}
          --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
          --create-plugin-repo

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.BOT_HUB_TOKEN }}
          repository: 3liz/3liz.github.io
          event-type: merge-plugins
          client-payload: '{"name": "wmtsCacheServer", "version": "${{ env.RELEASE_VERSION }}", "url": "https://github.com/3liz/qgis-server-wmts-cache-plugin/releases/latest/download/plugins.xml"}'
